const REGISTER = 'REGISTER';
const LOGIN = 'LOGIN';
const SET_IS_LOADING = 'SET_IS_LOADING';
const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';

export { REGISTER, LOGIN, SET_IS_LOADING, SET_IS_AUTHENTICATED };
